[tool.poetry]
name = "docat"
version = "0.0.0"
description = "Host your docs. Simple. Versioned. Fancy."
authors = ["Felix <hi@l33t.name>", "Benj <randombenj@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.9"
tinydb = "*"
fastapi = "^0.70.0"
Jinja2 = "^3.0.2"
python-multipart = "^0.0.5"
uvicorn = "^0.15.0"

[tool.poetry.dev-dependencies]
flake8 = "*"
flake8-isort = "*"
flake8-black = "*"
pytest = "*"
pytest-cov = "*"
mock = "*"
requests = "^2.26.0"
mypy = "^0.910"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "--ff -ra -v"
testpaths = [
    "tests"
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 140

[[tool.mypy.overrides]]
module = [
    "tinydb",
    "tinydb.storages",
    "uvicorn"
]
ignore_missing_imports = true

[tool.black]
line-length = 140
